version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/loom-network/go-loom
    steps:
      - checkout
      - run: make deps
      - run: make test
